### ISSUE TITLE
Error running python script

### ISSUE THREAD

**Issue by kittysher** [queenjobo/PhaseMyDeNovo#1]
Hello,

I am trying to phase my DNMs using the script provided. Here is an example of my input file:
child1  10      7487436 G       T       child1.vcf.gz|father.vcf.gz|mother.vcf.gz       child1_ID|father_ID|mother_ID   child1.cram
child1  10      36330124        G       A       child1.vcf.gz|father.vcf.gz|mother.vcf.gz       child1_ID|father_ID|mother_ID   child1.cram

And I run the script as:
python3 phase_my_denovos.py -dnmfile input_file -outfile phase_my_denovo_output

However I get this error after a few seconds:
Traceback (most recent call last):
  File "phase_my_denovos.py", line 250, in <module>
    main()
  File "phase_my_denovos.py", line 230, in main
    for id in dnms.id.unique():
  File "/anaconda/envs/PhaseMyDeNovos/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'id'

Please could you advise on what is going wrong? Also please could you provide some example data so I can see if the issue is with my data or the script?

Thanks
Kitty

**Comment by kittysher** [comment]
Hello. I was able to fix the above issue by adding column names to my input data. I can now run my script without getting any errors but the output file only has the column headings, and no data. The log file shows the list of input mutations.  I was able to phase some of these DNMs using denovogear, so I think something must be going wrong. Do you have any suggestions?

Many thanks
Kitty
